project_name: altid-cli
before:
  hooks:
    - go mod download
builds:
- binary: altid-cli
  main: ./cmd/altid-cli/main.go
  dir: ./cmd/altid-cli
  goos:
  - linux
  - windows
  - darwin
  - freebsd
  goarch: 
  - amd64
  - arm
  - arm64
  goarch:
  - 6
  - 7
  ignore:
  - goos: darwin
    goarch: arm
    goarch: arm64
  - goos: windows
    goarch: arm
    goarch: arm64
signs:
  - artifacts: all
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    freebsd: FreeBSD
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
