
// Objective-C API for talking to the following Go packages
//
//	github.com/altid/client
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Client_FRAMEWORK_H__
#define __Client_FRAMEWORK_H__

#include "Client.objc.h"
#include "Universe.objc.h"

#endif
