# Simple example to tie ii in to the framework

title = "ii config"

[menu]
save = ":save"
quit = ":quit"

# Location of buffers, in/out
[buffers]
main_out  = "~/local/run/ii/irc.freenode.net/#ubqt/out"
main_in   = "~/local/run/ii/irc.freenode.net/in"
other_out = "$XDG_RUNTIME_HOME/ii/.irc.*/*/out"
other_in  = "$XDG_RUNTIME_HOME/ii/irc.*/*/in"

# Have yet to decide how buffer swaps will occur
[navigation]
next = true
prev = false
