# Simple example to tie ii in to the framework

title = "ii config"

[menu]
save = ["save", "$XDG_RUNTIME_HOME/ii/in"]
quit = ["quit", "$XDG_RUNTIME_HOME/ii/in"]

# Location of buffers, in/out
[buffers]
main  = ['$XDG_RUNTIME_HOME/ii/irc.*/out', '$XDG_RUNTIME_HOME/ii/irc.*/in']
other = ['$XDG_RUNTIME_HOME/ii/.irc.*/*/out', '$XDG_RUNTIME_HOME/ii/irc.*/*/in']

# Have yet to decide how buffer swaps will occur
[navigation]
next = true
prev = false
