# Simple example to tie ii in to the framework

title = "ii config"

[menu]
save = "$XDG_RUNTIME_HOME/ii/in"
quit = "$XDG_RUNTIME_HOME/ii/in"

# Location of buffers, in/out
[buffers]
main_out  = "$XDG_RUNTIME_HOME/ii/irc.*/out"
main_in   = "$XDG_RUNTIME_HOME/ii/irc.*/in"
other_out = "$XDG_RUNTIME_HOME/ii/.irc.*/*/out"
other_in  = "$XDG_RUNTIME_HOME/ii/irc.*/*/in"

# Have yet to decide how buffer swaps will occur
[navigation]
next = true
prev = false
